apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: sqlinstance-hideichi-private-ip
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro
    ipConfiguration:
      ipv4Enabled: false
      privateNetworkRef:
        name: sqlinstance-dep-private-ip
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: sqlinstance-dep-private-ip
spec:
  addressType: INTERNAL
  location: global
  purpose: VPC_PEERING
  prefixLength: 16
  networkRef:
    name: sqlinstance-dep-private-ip
---
apiVersion: servicenetworking.cnrm.cloud.google.com/v1beta1
kind: ServiceNetworkingConnection
metadata:
  name: sqlinstance-dep-private-ip
spec:
  networkRef:
    name: sqlinstance-dep-private-ip
  reservedPeeringRanges:
    - name: sqlinstance-dep-private-ip
  service: servicenetworking.googleapis.com
