---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <deployment-name>
  namespace: <namespace>
spec:
  selector:
    matchLabels:
      app: <app-name>
  template:
    metadata:
      labels:
        app: <app-name>
    spec:
      serviceAccountName: <ksa-name>
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Always
        tty: true
        env: 
        - name: WORDPRESS_DB_HOST
          value: "127.0.0.1:3306"
        - name: WORDPRESS_DB_USER
          value: "wordpress"
        - name: WORDPRESS_DB_PASSWORD
          value: "wordpress"
        - name: WORDPRESS_DB_NAME
          value: "test_db"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          # GCPのsqlinstanceから接続名を持ってくる
          - "-instances=<sqlinstance_connection_name>=tcp:<db_port>"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "1Gi"
            cpu:    "100m"
        ports:
        - containerPort: <db_port>
      - name: wew
        image: imega/mysql-client
        command: ["/bin/sh","-c" ,"sleep 90000"]
        resources:
          requests:
            memory: "1Gi"
            cpu:    "100m"
...
---
# ロードバランサー　外部から通でアクセス出来るように
apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
  namespace: <namespace>
spec:
  selector:
    app: <app-name>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
...
